subgraphs:
  users:
    routing_url: http://localhost:4000
    schema:
      subgraph_url: http://localhost:4000
  social:
    routing_url: http://localhost:4002
    schema:
      subgraph_url: http://localhost:4002